menu_items = [
    {"number": "1", "dish": "Eierblumensuppe (m. Hühnerfleisch)", "price_eur": 3.50},
    {"number": "5", "dish": "Tom Kha Gai Suppe (m. Hühnerfl. u. Kokosmilch)", "price_eur": 4.00},
    {"number": "6", "dish": "Tom Yam-Gung Thai-Suppe mit Garnelen", "price_eur": 4.00},
    {"number": "7", "dish": "Sauer-Scharf-Suppe (m. Hühnerfleisch)", "price_eur": 3.50},
    {"number": "8", "dish": "Wan-Tan-Suppe (m. Hühnerfleisch-Füllung)", "price_eur": 3.50},
    {"number": "9", "dish": "Glasnudeln-Suppe mit Hühnerfleisch", "price_eur": 3.50},
    {"number": "18", "dish": "Frühlingsrollen vegetarisch (8 Stück)", "price_eur": 3.50},
    {"number": "19", "dish": "Wan-Tan gebacken (6 Stück)", "price_eur": 3.50},
    {"number": "21", "dish": "Hühnerfleisch (klein)", "price_eur": 6.00},
    {"number": "23", "dish": "Vegetarisch", "price_eur": 6.00},
    {"number": "24", "dish": "Hühnerfleisch (groß)", "price_eur": 7.00},
    {"number": "25", "dish": "Rindfleisch", "price_eur": 9.00},
    {"number": "26", "dish": "Ente paniert, kross u. Süß-Sauer-Sauce", "price_eur": 10.00},
    {"number": "27", "dish": "Hühnerbrust kross u. Süß-Sauer-Sauce", "price_eur": 9.00},
    {"number": "28", "dish": "Bami-Goreng m. Hühnerfleisch und Shrimps (Curry, pikant)", "price_eur": 8.50},
    {"number": "29", "dish": "Garnelen (8 Stück)", "price_eur": 10.00},
    {"number": "31", "dish": "Hühnerfleisch (klein)", "price_eur": 6.00},
    {"number": "33", "dish": "Vegetarisch", "price_eur": 6.00},
    {"number": "34", "dish": "Hühnerfleisch (groß)", "price_eur": 7.00},
    {"number": "35", "dish": "Rindfleisch", "price_eur": 9.00},
    {"number": "36", "dish": "Ente paniert, kross u. Süß-Sauer-Sauce", "price_eur": 10.00},
    {"number": "37", "dish": "Hühnerbrust kross u. Süß-Sauer-Sauce", "price_eur": 9.00},
    {"number": "38", "dish": "Nasi Goreng m. Hühnerfleisch und Shrimps (Curry, pikant)", "price_eur": 8.50},
    {"number": "39", "dish": "Garnelen (8 Stück)", "price_eur": 10.00},
    {"number": "40", "dish": "Tofu", "price_eur": 7.50},
    {"number": "41", "dish": "Hühnerfleisch", "price_eur": 8.50},
    {"number": "42", "dish": "Hühnerbrust doppelt gebacken", "price_eur": 9.00},
    {"number": "43", "dish": "Rindfleisch", "price_eur": 9.00},
    {"number": "47", "dish": "Pad-Thai gebr. Reisbandnudeln m. Hühnerfleisch, Gemüse und Erdnüsse (pikant)", "price_eur": 8.50},
    {"number": "50", "dish": "Vegetarisch mit Tofu", "price_eur": 7.50},
    {"number": "51a", "dish": "Hühnerfleisch", "price_eur": 7.50},
    {"number": "51b", "dish": "Hühnerbrust in Stück doppelt gebacken", "price_eur": 9.00},
    {"number": "52", "dish": "Rindfleisch", "price_eur": 9.00},
    {"number": "53", "dish": "Ente paniert kross gebacken", "price_eur": 10.00},
    {"number": "54", "dish": "Garnelen (8 Stück)", "price_eur": 10.00},
    {"number": "55", "dish": "Hühnerbrust in Scheiben kross gebacken", "price_eur": 9.00},
    {"number": "56", "dish": "Tofu (pikant, nach Thai-Art)", "price_eur": 7.50},
    {"number": "57a", "dish": "Hühnerbrust (pikant, nach Thai-Art)", "price_eur": 7.50},
    {"number": "57b", "dish": "Hühnerbrust in Stück doppelt gebacken", "price_eur": 9.00},
    {"number": "57c", "dish": "Hühnerbrust in Scheiben kross gebacken", "price_eur": 9.00},
    {"number": "58", "dish": "Garnelen (8 Stück) pikant, nach Thai-Art", "price_eur": 10.00},
    {"number": "59", "dish": "Ente paniert kross gebacken", "price_eur": 10.00},
    {"number": "60", "dish": "Vegetarisch mit Tofu", "price_eur": 7.50},
    {"number": "61", "dish": "Hühnerfleisch", "price_eur": 8.50},
    {"number": "62", "dish": "Rindfleisch", "price_eur": 9.00},
    {"number": "63", "dish": "Ente paniert kross gebacken", "price_eur": 10.00},
    {"number": "64", "dish": "Garnelen (8 Stück)", "price_eur": 10.00},
    {"number": "65", "dish": "Hühnerbrust paniert kross gebacken", "price_eur": 9.00},
    {"number": "80", "dish": "Vegetarisch mit Tofu", "price_eur": 7.50},
    {"number": "81", "dish": "Hühnerfleisch", "price_eur": 8.50},
    {"number": "83", "dish": "Ente paniert kross gebacken", "price_eur": 10.00},
    {"number": "85", "dish": "Hühnerbrust paniert kross gebacken", "price_eur": 9.00},
    {"number": "90", "dish": "Vegetarisch mit Tofu", "price_eur": 7.50},
    {"number": "91", "dish": "Hühnerfleisch", "price_eur": 8.50},
    {"number": "92", "dish": "Rindfleisch", "price_eur": 9.00},
    {"number": "93", "dish": "Ente paniert kross gebacken", "price_eur": 10.00},
    {"number": "95", "dish": "Hühnerbrust paniert kross gebacken", "price_eur": 9.00},
    {"number": "100", "dish": "Vegetarisch mit Tofu", "price_eur": 7.50},
    {"number": "101", "dish": "Hühnerfleisch", "price_eur": 8.50},
    {"number": "102", "dish": "Rindfleisch", "price_eur": 9.00},
    {"number": "103", "dish": "Ente paniert kross gebacken", "price_eur": 10.00},
    {"number": "105", "dish": "Hühnerbrust paniert kross gebacken", "price_eur": 9.00},
    {"number": "110", "dish": "Vegetarisch mit Tofu", "price_eur": 7.50},
    {"number": "111", "dish": "Hühnerfleisch", "price_eur": 8.50},
    {"number": "112", "dish": "Rindfleisch", "price_eur": 9.00},
    {"number": "113", "dish": "Ente paniert kross gebacken", "price_eur": 10.00},
    {"number": "115", "dish": "Hühnerbrust paniert kross gebacken", "price_eur": 9.00},
    {"number": "120", "dish": "Vegetarisch mit Tofu", "price_eur": 7.50},
    {"number": "121", "dish": "Hühnerfleisch", "price_eur": 8.50},
    {"number": "123", "dish": "Ente paniert kross gebacken", "price_eur": 10.00},
    {"number": "124", "dish": "Hühnerbrust paniert kross gebacken", "price_eur": 9.00}
]
